version: '3.8'

services:
  # Backend API Service
  api:
    image: api-image
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "4000:4000"
    env_file: .env

  # Remix App Service
  app:
    image: app-image
    build:
      context: .
      dockerfile: Dockerfile.app
    ports:
      - "80:3000"
    env_file: .env

