# Use the official Node.js image
FROM node:20

# Create app directory
WORKDIR /usr/src/app



# Install Bun and configure PATH
RUN curl -fsSL https://bun.sh/install | bash
ENV BUN_INSTALL="/root/.bun"
ENV PATH="$BUN_INSTALL/bin:$PATH"
RUN bun --version


# Install app dependencies
COPY package*.json ./
RUN npm install -g pnpm
RUN pnpm install

# Bundle app source
COPY . .

RUN npx prisma db push
# Expose port and start the app
EXPOSE 4000
CMD ["npm", "run", "api:start"]

