# Use the official Node.js image
FROM node:20

# Create app directory
WORKDIR /usr/src/app



# Install Bun and configure PATH
RUN curl -fsSL https://bun.sh/install | bash
ENV BUN_INSTALL="/root/.bun"
ENV PATH="$BUN_INSTALL/bin:$PATH"
RUN bun --version

# Install app dependencies
COPY package*.json ./
RUN npm install

# Bundle app source
COPY . .

# Command to run the migrations
CMD ["npm", "run", "db:migrate"]
