name = "splitbox-sender-cron"
main = "cron/index.ts"
compatibility_date = "2024-03-12"
node_compat = true

# Cron Triggers
# Docs: https://developers.cloudflare.com/workers/platform/triggers/cron-triggers/
# Configuration: https://developers.cloudflare.com/workers/wrangler/configuration/#triggers
[triggers]
crons = ["59 * * * *"] # * * * * * = run every minute
