export const countries = {
  Afghanistan: 'afghanistan',
  Albania: 'albania',
  Algeria: 'algeria',
  Andorra: 'andorra',
  Angola: 'angola',
  'Antigua and Barbuda': 'antigua_and_barbuda',
  Argentina: 'argentina',
  Armenia: 'armenia',
  Australia: 'australia',
  Austria: 'austria',
  Azerbaijan: 'azerbaijan',
  Bahamas: 'bahamas',
  Bahrain: 'bahrain',
  Bangladesh: 'bangladesh',
  Barbados: 'barbados',
  Belarus: 'belarus',
  Belgium: 'belgium',
  Belize: 'belize',
  Benin: 'benin',
  Bhutan: 'bhutan',
  Bolivia: 'bolivia',
  'Bosnia and Herzegovina': 'bosnia_and_herzegovina',
  Botswana: 'botswana',
  Brazil: 'brazil',
  Brunei: 'brunei',
  Bulgaria: 'bulgaria',
  'Burkina Faso': 'burkina_faso',
  Burundi: 'burundi',
  'Côte d\'Ivoire': 'cote_d\'ivoire',
  'Cabo Verde': 'cabo_verde',
  Cambodia: 'cambodia',
  Cameroon: 'cameroon',
  Canada: 'canada',
  'Central African Republic': 'central_african_republic',
  Chad: 'chad',
  Chile: 'chile',
  China: 'china',
  Colombia: 'colombia',
  Comoros: 'comoros',
  'Congo (Congo-Brazzaville)': 'congo',
  'Costa Rica': 'costa_rica',
  Croatia: 'croatia',
  Cuba: 'cuba',
  Cyprus: 'cyprus',
  'Czechia (Czech Republic)': 'czech_republic',
  'Democratic Republic of the Congo': 'democratic_republic_of_the_congo',
  Denmark: 'denmark',
  Djibouti: 'djibouti',
  Dominica: 'dominica',
  'Dominican Republic': 'dominican_republic',
  Ecuador: 'ecuador',
  Egypt: 'egypt',
  'El Salvador': 'el_salvador',
  'Equatorial Guinea': 'equatorial_guinea',
  Eritrea: 'eritrea',
  Estonia: 'estonia',
  'Eswatini (fmr. "Swaziland")': 'eswatini',
  Ethiopia: 'ethiopia',
  Fiji: 'fiji',
  Finland: 'finland',
  France: 'france',
  Gabon: 'gabon',
  Gambia: 'gambia',
  Georgia: 'georgia',
  Germany: 'germany',
  Ghana: 'ghana',
  Greece: 'greece',
  Grenada: 'grenada',
  Guatemala: 'guatemala',
  Guinea: 'guinea',
  'Guinea-Bissau': 'guinea_bissau',
  Guyana: 'guyana',
  Haiti: 'haiti',
  'Holy See': 'holy_see',
  Honduras: 'honduras',
  Hungary: 'hungary',
  Iceland: 'iceland',
  India: 'india',
  Indonesia: 'indonesia',
  Iran: 'iran',
  Iraq: 'iraq',
  Ireland: 'ireland',
  Israel: 'israel',
  Italy: 'italy',
  Jamaica: 'jamaica',
  Japan: 'japan',
  Jordan: 'jordan',
  Kazakhstan: 'kazakhstan',
  Kenya: 'kenya',
  Kiribati: 'kiribati',
  Kuwait: 'kuwait',
  Kyrgyzstan: 'kyrgyzstan',
  Laos: 'laos',
  Latvia: 'latvia',
  Lebanon: 'lebanon',
  Lesotho: 'lesotho',
  Liberia: 'liberia',
  Libya: 'libya',
  Liechtenstein: 'liechtenstein',
  Lithuania: 'lithuania',
  Luxembourg: 'luxembourg',
  Madagascar: 'madagascar',
  Malawi: 'malawi',
  Malaysia: 'malaysia',
  Maldives: 'maldives',
  Mali: 'mali',
  Malta: 'malta',
  'Marshall Islands': 'marshall_islands',
  Mauritania: 'mauritania',
  Mauritius: 'mauritius',
  Mexico: 'mexico',
  Micronesia: 'micronesia',
  Moldova: 'moldova',
  Monaco: 'monaco',
  Mongolia: 'mongolia',
  Montenegro: 'montenegro',
  Morocco: 'morocco',
  Mozambique: 'mozambique',
  'Myanmar (formerly Burma)': 'myanmar',
  Namibia: 'namibia',
  Nauru: 'nauru',
  Nepal: 'nepal',
  Netherlands: 'netherlands',
  'New Zealand': 'new_zealand',
  Nicaragua: 'nicaragua',
  Niger: 'niger',
  Nigeria: 'nigeria',
  'North Korea': 'north_korea',
  'North Macedonia (formerly Macedonia)': 'north_macedonia',
  Norway: 'norway',
  Oman: 'oman',
  Pakistan: 'pakistan',
  Palau: 'palau',
  'Palestine State': 'palestine',
  Panama: 'panama',
  'Papua New Guinea': 'papua_new_guinea',
  Paraguay: 'paraguay',
  Peru: 'peru',
  Philippines: 'philippines',
  Poland: 'poland',
  Portugal: 'portugal',
  Qatar: 'qatar',
  Romania: 'romania',
  Russia: 'russia',
  Rwanda: 'rwanda',
  'Saint Kitts and Nevis': 'saint_kitts_and_nevis',
  'Saint Lucia': 'saint_lucia',
  'Saint Vincent and the Grenadines': 'saint_vincent_and_the_grenadines',
  Samoa: 'samoa',
  'San Marino': 'san_marino',
  'Sao Tome and Principe': 'sao_tome_and_principe',
  'Saudi Arabia': 'saudi_arabia',
  Senegal: 'senegal',
  Serbia: 'serbia',
  Seychelles: 'seychelles',
  'Sierra Leone': 'sierra_leone',
  Singapore: 'singapore',
  Slovakia: 'slovakia',
  Slovenia: 'slovenia',
  'Solomon Islands': 'solomon_islands',
  Somalia: 'somalia',
  'South Africa': 'south_africa',
  'South Korea': 'south_korea',
  'South Sudan': 'south_sudan',
  Spain: 'spain',
  'Sri Lanka': 'sri_lanka',
  Sudan: 'sudan',
  Suriname: 'suriname',
  Sweden: 'sweden',
  Switzerland: 'switzerland',
  Syria: 'syria',
  Tajikistan: 'tajikistan',
  Tanzania: 'tanzania',
  Thailand: 'thailand',
  'Timor-Leste': 'timor_leste',
  Togo: 'togo',
  Tonga: 'tonga',
  'Trinidad and Tobago': 'trinidad_and_tobago',
  Tunisia: 'tunisia',
  Turkey: 'turkey',
  Turkmenistan: 'turkmenistan',
  Tuvalu: 'tuvalu',
  Uganda: 'uganda',
  Ukraine: 'ukraine',
  'United Arab Emirates': 'united_arab_emirates',
  'United Kingdom': 'united_kingdom',
  'United States': 'united_states',
  Uruguay: 'uruguay',
  Uzbekistan: 'uzbekistan',
  Vanuatu: 'vanuatu',
  Venezuela: 'venezuela',
  Vietnam: 'vietnam',
  Yemen: 'yemen',
  Zambia: 'zambia',
  Zimbabwe: 'zimbabwe',
} as const;

