name: Deploy App to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to VPS
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << 'EOF'
          cd ${{ secrets.VPS_PATH }}
          git stash
          source /home/${{ secrets.VPS_USER }}/.bashrc 
          echo "${{secrets.SSH_PRIVATE_KEY}}"
          alias node=/home/semere/.local/share/fnm/node-versions/v20.13.1/installation/bin/node
          alias npm=/home/semere/.local/share/fnm/node-versions/v20.13.1/installation/bin/npm
          alias npx=/home/semere/.local/share/fnm/node-versions/v20.13.1/installation/bin/npx
          /home/${{ secrets.VPS_USER }}/.local/share/fnm/fnm use 20
          # Find and kill the process running npm start
          pkill -f "npm run app:start"
          git pull origin main
          npm install
          npm run db:migrate
          npm run app:build
          nohup npm run app:start & 
        EOF

